name: Selenium Web Scrapping Workflow Testing
on:
  push: 
    branches: [ main ]

jobs:
  scrapper-code:
    runs-on: ubuntu-latest
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/python@v4
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          chromedriver-version: 'latest'
          headless: true
      - name: Run main.py
      run: python main.py
